apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
spec:
  type: NodePort
  selector:
    app: devops-project
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
